require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - Rakefile
    - Guardfile
    - bin/*
    - tmp/**/*
    - node_modules/**/*
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions:
    rubocop-sequel: false

Style:
  Enabled: false

Layout:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - "spec/**/*.rb"
    - "test/**/*.rb"
    - "Rakefile"
    - "*.gemspec"
    - "apps/api/application.rb"
    - "**/*.rake"

Metrics/ClassLength:
  CountComments: false
  Exclude:
    - "spec/**/*.rb"
    - "test/**/*.rb"

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - "spec/**/*.rb"
    - "test/**/*.rb"

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - "spec/**/*.rb"
    - "test/**/*.rb"

# RSpec config
# When adding a new setting below here, please provide a reason with it.

# Excluded for some folders because we want this rule only for unit specs
RSpec/DescribeClass:
  Exclude:
    - spec/features/*
    - spec/integration/*

# Avoid filename issues with Minitest filenames
RSpec/FilePath:
  Exclude:
    - "test/**/*.rb"

# Next to the advantages, the check for verified doubles also means that
# something about Y being checked in a spec that is about X, which is not
# really clean. So it's not enabled by default.
# refs https://relishapp.com/rspec/rspec-mocks/docs/verifying-doubles
RSpec/VerifiedDoubles:
  Enabled: false

# There are cases for meta-programming where adding an empty class is useful and
# should be allowed.
Lint/EmptyClass:
  Enabled: false

# The standard library has methods like `iso8601` which trigger this rule, so
# it's better to allow iso8601 for those as well as things like `foo_2` in our # code
Naming/VariableNumber:
  Enabled: false

###
# Disabled initially
###
RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
